fix: publish dist folder
equinor/dm-core-packages pull request #11
Opened 2022-10-05 07:24 UTC by KristianKjerstad

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change

2022-10-05 13:06 UTC, KristianKjerstad commented on packages/dmt-core/package.json
> +    "src"
adding src was necessary to make source map work

2022-10-05 13:40 UTC, netr0m approved these changes

2022-10-06 05:45 UTC, soofstad approved these changes

2022-10-06 13:02 UTC, rikkebl requested changes
Please see remark

2022-10-07 10:45 UTC, merged