feat: stack plugin
equinor/dm-core-packages pull request #1276
Opened 2024-02-07 11:57 UTC by awesthouse

## What does this pull request change?
Add StackPlugin to dm-core-plugins. Allows user to stack views on top or next to each other.
In items array, just pass viewConfig objects

Example of config:
```json
{
      "name": "Dashboard",
      "type": "CORE:UiRecipe",
      "description": "ESS Plot",
      "plugin": "@development-framework/dm-core-plugins/stack",
      "config": {
        "type": "PLUGINS:dm-core-plugins/stack/StackPluginConfig",
        "items": [
          {
            "type": "CORE:ReferenceViewConfig",
            "scope": "sce",
            "recipe": "Date"
          },
          {
            "type": "CORE:ReferenceViewConfig",
            "scope": "job",
            "recipe": "Fetch_Signals_OmniaTS"
          },
          {
            "type": "CORE:ReferenceViewConfig",
            "scope": "sce.signals",
            "recipe": "List"
          }
        ]
      }
    },
```

Open to discussing naming. "MultiView" to me seems like you can switch between multiple views of the same content. "Flexbox" is more css language. If we describe this as user being able to **stack** views on top of or next to each other - I feel like it's pretty self-explanatory. 

## Why is this pull request needed?
Help with some layout use-cases that are a bit over-complicated.

## Issues related to this change
#1239 & #1258

2024-02-07 13:41 UTC, pbullhove requested changes

2024-02-08 09:02 UTC, awesthouse commented on packages/dm-core-plugins/blueprints/stack/StackPluginConfig.json
> +      "default": "horizontal"
I definitely seemed to have mixed up directions here - will fix 😆

2024-02-08 09:03 UTC, awesthouse commented on packages/dm-core-plugins/blueprints/stack/StackPluginConfig.json
> +      "description": "When using vertical direction, make items wrap under eachother when width is getting too small to fit all items",
I just don't think max-height is something you want to constrain that often (also for ux purposes). I also added the classNames prop, so if you configure tailwind for your project, you can pretty much add any styling you want to the wrapper

2024-02-08 09:08 UTC, awesthouse commented on packages/dm-core-plugins/blueprints/stack/StackPluginConfig.json
> +      "description": "REM value. Default is 2 = 32px",
I understand people are familiar with px, but it's bad practice on things like spacing and padding. Even tailwind uses some form of mapping for a number value -> rem. https://tailwindcss.com/docs/space 

I think it's something you can easily familiarize yourself with if it's a standard practice. If the default is 2 and you want less, you know the number has to be lower, same with bigger. Using rem for padding and spacing (and sometimes width, height) should be what we introduce for our entire application.

Open to discussing more 🙂

2024-02-08 09:10 UTC, awesthouse commented on packages/dm-core-plugins/blueprints/stack/StackPluginConfig.json
> +      "description": "When using vertical direction, make items wrap under eachother when width is getting too small to fit all items",
Also don't know if flexbox allows for wrapping item that way - will check, but I'm pretty sure the flex-wrap: wrap would be the same styling required so we don't need to change anything anyways

2024-02-08 10:04 UTC, pbullhove approved these changes
LGTM

2024-02-08 10:04 UTC, pbullhove commented on packages/dm-core-plugins/blueprints/stack/StackPluginConfig.json
> +      "description": "REM value. Default is 2 = 32px",
ok

2024-02-08 12:37 UTC, merged