_fix: update Package entities to have correct type
equinor/dm-core-packages pull request #190
Opened 2023-04-21 12:41 UTC by KristianKjerstad

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change

https://github.com/equinor/dm-core-packages/issues/189

2023-04-21 13:53 UTC, KristianKjerstad commented
needs https://github.com/equinor/data-modelling-storage-service/pull/406

2023-04-24 11:13 UTC, soofstad requested changes

2023-04-24 11:13 UTC, soofstad commented on packages/dm-core-plugins/blueprints/attribute-selector/package.json
> +    "type": "dmss://system/SIMOS/Meta",
Should not be necessary

2023-04-27 08:41 UTC, soofstad commented
no longer needed as of : https://github.com/equinor/dm-cli/pull/88

2023-04-27 08:41 UTC, closed without merging