feature: add 'initialRecipeSelector' and SidebarRecipeSelector
equinor/dm-core-packages pull request #54
Opened 2023-01-24 08:52 UTC by soofstad

## What does this pull request change?
- Adds a new meta "RecipeSelector-Selector" - treat UiPluginSelector and UiPluginSideBarSelector as plugins
- Adds a new UiPluginSideBarSelector for concept demo and testing purposes

## Why is this pull request needed?
Need a generic "recipeSelector" that respects "initialRecipe"

## Issues related to this change
closes #53

2023-01-24 14:52 UTC, KristianKjerstad requested changes

2023-01-24 14:52 UTC, KristianKjerstad commented on packages/dm-core/src/components/UiRecipesSideBarSelector.tsx
> +  const { uiRecipes, isLoading } = useBlueprint(type)
suggestion: 
rename loading to isContextLoading
and isLoading to isBlueprintLoading

2023-01-24 14:52 UTC, KristianKjerstad commented on packages/dm-core/src/components/UiRecipesSideBarSelector.tsx
> +    // @ts-ignore
can this ts-ignore be deleted if we add a return type to the function inside the above map function?


```JavaScript
    const recipes = uiRecipes.map((uiRecipe: any): TSelectablePlugins => ({
      name: uiRecipe?.label || uiRecipe?.name || uiRecipe?.plugin || 'No name',
      component: getUiPlugin(uiRecipe?.plugin).component,
      config: uiRecipe?.config,
    }))
```

2023-01-24 14:52 UTC, KristianKjerstad commented on example/src/App.js
> +          <>Loading...</>
Can replace with 
```JavaScript
      <div style={{ alignSelf: 'center', padding: '50px' }}>
        <CircularProgress color="primary" />
      </div>
```

but not a big deal

2023-01-24 14:52 UTC, KristianKjerstad commented on packages/dm-core/src/components/UiRecipesSelector.tsx
> +  const { loading, getUiPlugin } = useContext(UiPluginContext)
suggestion:
rename loading to isContextLoading
and isLoading to isBlueprintLoading

2023-01-24 14:52 UTC, KristianKjerstad commented on packages/dm-core/src/components/UiRecipesSelector.tsx
> +    let Component
```suggestion
    let component
```
camelcase

2023-01-24 14:52 UTC, KristianKjerstad commented on packages/dm-core/src/components/UiRecipesSelector.tsx
> +  if (isLoading)
should circular progress also be displayed when loading = True? (loading context)

2023-01-24 14:52 UTC, KristianKjerstad commented on packages/dm-core/src/components/UiPluginSelector.tsx
> +  const { uiRecipes, isLoading, error } = useBlueprint(type)
suggestion:
rename loading to isContextLoading
and isLoading to isBlueprintLoading

2023-01-27 13:31 UTC, eoaksnes commented on example/src/App.js
> +              console.log(node)
console.log

2023-01-27 13:43 UTC, eoaksnes approved these changes
Nice!

2023-01-30 09:28 UTC, merged