Feat/media viewer
equinor/dm-core-packages pull request #734
Opened 2023-11-15 08:40 UTC by henrikbossart

## What does this pull request change?
Media viewer to view media objects (File)

## Why is this pull request needed?

## Issues related to this change

![Screenshot 2023-11-15 at 09 40 12](https://github.com/equinor/dm-core-packages/assets/3105885/1b2f2914-cdbe-4c32-b245-ab068bf84e31)

2023-11-16 08:46 UTC, soofstad requested changes
Looks great!
A few comments on structure

2023-11-16 08:46 UTC, soofstad commented on example/app/data/DemoDataSource/apps/ExampleApplication/blueprints/MediaObject.blueprint.json
Sure we need this wrapper for the "File"?
We shouldn't

2023-11-16 08:46 UTC, soofstad commented on example/app/data/DemoDataSource/apps/ExampleApplication/blueprints/ExampleApplication.blueprint.json
Could we add the test blueprint and entities to "DemoDataSource/plugins/media_viewer", so it follows the structure of the other plugins and their tests

2023-11-16 08:46 UTC, soofstad commented on example/app/data/DemoDataSource/recipes/apps/ExampleApplication/mediaObject.recipe.json
> +  "_blueprintPath_": "/apps/ExampleApplication/blueprints/MediaObject",
I'd imagine this recipe would be for the "File" type instead.

2023-11-16 08:46 UTC, soofstad commented on example/app/data/DemoDataSource/recipes/file.recipe.json
> +            },
Should remove this "recipe", with the "ViewConfig" type. "media-viewer" would then be selected automatically.

2023-11-16 08:46 UTC, soofstad commented on packages/dm-core-plugins/src/mediaViewer/MediaContent.tsx
> +  //mix-blend-mode: difference;
```suggestion
```

2023-11-16 08:46 UTC, soofstad commented on packages/dm-core-plugins/src/mediaViewer/MediaContent.tsx
> +        {meta.filetype !== 'application/pdf' && (
Could this be a "select case" instead? Would that make it more readable?

2023-11-16 08:46 UTC, soofstad commented on packages/dm-core-plugins/src/mediaViewer/MediaViewerPlugin.tsx
> +  if (document.data.type !== EBlueprint.FILE) return <>Error: Not File type</>
This might as well throw an Error

2023-11-16 08:58 UTC, henrikbossart commented on example/app/data/DemoDataSource/apps/ExampleApplication/blueprints/MediaObject.blueprint.json
No, I don't think we need it. Forgot to write about it in the description, but I didn't manage to just add the plugin for the File, so I had to create a separate entity/BP/recipe for it.

2023-11-16 18:48 UTC, henrikbossart commented
Not quite sure I'm doing the blueprint/recipe/entity thing correctly, so I'll grab one of you guys tomorrow :+1:

2023-11-17 08:23 UTC, henrikbossart commented
@soofstad please take a look at my recent changes regarding blueprints etc. I've changed it so that the file is rendered by the new media viewer by default, without the viewselector

2023-11-17 12:48 UTC, soofstad approved these changes
Looks good!

2023-11-17 12:48 UTC, soofstad commented on example/app/data/DemoDataSource/plugins/media_viewer/assets/pain.mov
Would be nice to keep some test video. But if you can find a bit smaller one? :sweat_smile:

2023-11-20 08:48 UTC, merged