Feat/select recipes in header plugin
equinor/dm-core-packages pull request #84
Opened 2023-02-07 16:16 UTC by KristianKjerstad

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change

2023-02-08 15:10 UTC, KristianKjerstad commented on packages/header/src/Header.tsx
> +  const idRef = 'DemoDataSource/46a2c6ce-5bb4-41bc-923e-ede8dc95500e'
Not sure how to deal with these two hard coded values. Perhaps let is be part of config instead?

2023-02-09 07:50 UTC, KristianKjerstad commented on packages/header/src/components/UserInfoDialog.tsx
> +import { Icon, Radio, TopBar } from '@equinor/eds-core-react'
this stuff is copied from old Header plugin

2023-02-09 12:59 UTC, soofstad requested changes

2023-02-09 12:59 UTC, soofstad commented on example/app/data/DemoDataSource/DemoPackage/recipe_links/example_application.json
> +      "uiPluginsList": ["yaml-view", "explorer"],
I think you should select recipes here, not plugins.

2023-02-09 12:59 UTC, soofstad commented on packages/header/README.md
> +* `uiPluginsList`: Can be used to specify a list of UI plugins the user can select. By default, the fist UI plugin in
Recipes, not plugins

2023-02-09 12:59 UTC, soofstad commented on packages/header/README.md
> +  the list is displayed. If the list is empty, no plugin is displayed. NB! All plugins listed here must be included in
Really think the header should use all recipes if the "uiPluginsList" is empty.
Sane defaults and minimum amount of config being the goal.

2023-02-09 12:59 UTC, soofstad commented on packages/header/package.json
> +    "@development-framework/form": "^1.0.0",
Should not be added here.
Instead should be loaded from the dm-core "UiPluginsContext". Similar to what is done in "UiPluginsSelector".

2023-02-09 12:59 UTC, soofstad commented on packages/header/src/components/PluginSelector.tsx
> +export const PluginSelector = (props: RecipeSelectorProps) => {
Make sure not to use "Plugin" and "Recipe" interchangeably. They are not the same :)

2023-02-14 06:52 UTC, soofstad approved these changes

2023-02-14 06:52 UTC, soofstad commented on example/app/data/DemoDataSource/DemoPackage/HeaderPluginConfig.json
> +      "name": "uiPluginsList"
```suggestion
      "name": "uiRecipesList"
```

2023-02-14 06:52 UTC, soofstad commented on packages/header/src/Header.tsx
> +                setSelectedPlugin({ component: getUiPlugin(uiPluginName) })
```suggestion
                setAppSelectorOpen(false)
                setSelectedPlugin({ component: getUiPlugin(uiPluginName) })
```

2023-02-14 06:52 UTC, soofstad commented on packages/header/src/plugins.js
> +  import('@development-framework/default-pdf'),
This file should be deleted no?

2023-02-14 06:52 UTC, soofstad commented on packages/header/src/types.ts
> +  adminRole: string
These should be optional. 
Not every app will need them, but they should still be able to use the header plugin

2023-02-15 07:50 UTC, merged