Use official biome pre-commit hook
equinor/dm-core-packages pull request #958
Opened 2023-12-13 09:22 UTC by henrikbossart

## What does this pull request change?
Replaces the local hook with the official biome pre-commit hook.

## Why is this pull request needed?

## Issues related to this change

2023-12-13 11:37 UTC, eoaksnes approved these changes

2023-12-13 12:15 UTC, soofstad requested changes
This is still a "local" repo hook :o 
Can have a look at the link provided in the issue on how it should be added.

2023-12-21 06:08 UTC, henrikbossart commented
I'm really struggling to make this file ignoring work. Could someone with more pre-commit experience please take a look at my pattern? 🙏

2023-12-22 10:35 UTC, soofstad approved these changes

2023-12-22 11:04 UTC, merged